/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/env.d.ts` (hash: e2c6acb711fab5ed21d07a67a5ccb1eb)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
  DEMO_ORIGINS:
    | "https://voiceinput.dev"
    | "http://127.0.0.1:4322,http://127.0.0.1:4321,http://localhost:4321";
  OPENAI_API_KEY: string;
  DEMO_GUARD: DurableObjectNamespace<import("./index").DemoGuard>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
    durableNamespaces: "DemoGuard";
  }
  interface ProductionEnv {
    ASSETS: Fetcher;
    DEMO_ORIGINS: "https://voiceinput.dev";
    OPENAI_API_KEY: string;
    DEMO_GUARD: DurableObjectNamespace<import("./index").DemoGuard>;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "DEMO_ORIGINS" | "OPENAI_API_KEY">
  > {}
}
